[project]
name = "speech_preprocess"
version = "0.1.0"
description = "Pre-process speech datasets"
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "Maxime Poli" }]
dependencies = [
  "joblib>=1.5.3",
  "numpy>=2.4.4",
  "polars>=1.40.1",
  "pyannote-audio>=4.0.4",
  "pyannote-core>=6.0.1",
  "torch>=2.12.0",
  "torchcodec>=0.14.0",
  "tqdm>=4.67.3",
]

[project.scripts]
speech-preprocess = "speech_preprocess.__main__:cli"

[dependency-groups]
dev = [
  "griffe>=1.7.3",
  "griffe2md>=1.3.0",
  "ipykernel>=7.2.0",
  "prek>=0.3.13",
]

[build-system]
requires = ["flit_core>=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.ruff]
line-length = 119

[tool.ruff.lint]
preview = true
select = [
  "A",  # flake8-builtins
  "ARG",  # flake8-unused-arguments
  "ANN",  # flake8-annotations
  "B",  # flake8-bugbear
  "BLE",  # flake8-blind-except
  "C4",  # flake8-comprehensions
  "C90",  # mccabe
  "E",  # pycodestyle error
  "EXE",  # flake8-executable
  "F",  # Pyflakes
  "FBT",  # flake8-boolean-trap
  "FLY",  # flynt
  "FURB",  # refurb
  "G",  # flake8-logging-format
  "I",  # isort
  "ICN",  # flake8-import-conventions
  "ISC",  # flake8-implicit-str-concat
  "LOG",  # flake8-logging
  "N",  # pep8-naming
  "NPY",  # NumPy-specific rules
  "PERF",  # Perflint
  "PIE",  # flake8-pie
  "PGH",  # pygrep-hooks
  "PL",  # Pylint
  "PTH",  # flake8-use-pathlib
  "Q",  # flake8-quotes
  "RET",  # flake8-return
  "RSE",  # flake8-raise
  "RUF",  # Ruff-specific rules
  "S",  # flake8-bandit
  "SIM",  # flake8-simplify
  "SLF",  # flake8-slots
  "T10",  # flake8-debugger
  "TC",  # flake8-type-checking
  "TD",  # flake8-todos
  "TID",  # flake8-tidy-imports
  "UP",  # pyupgrade
  "W",  # pycodestyle warning
]
ignore = ["S101"]

[tool.ruff.lint.pylint]
max-args = 7

[tool.uv.sources]
torch = [{ index = "pytorch-cu126" }]
torchaudio = [{ index = "pytorch-cu126" }]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true
